/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register/route'
import { Route as MeRouteImport } from './routes/me/route'
import { Route as LoginRouteImport } from './routes/login/route'
import { Route as VerifyEmailCodeRouteImport } from './routes/verify-email/$code/route'
import { Route as BuilderIdRouteImport } from './routes/builder/$id/route'
import { Route as BuilderIndexRouteImport } from './routes/builder/index/route'

// Create Virtual Routes

const ForgotPasswordRouteLazyImport = createFileRoute('/forgot-password')()
const IndexRouteLazyImport = createFileRoute('/')()
const ResetPasswordCodeRouteLazyImport = createFileRoute(
  '/reset-password/$code',
)()

// Create/Update Routes

const ForgotPasswordRouteLazyRoute = ForgotPasswordRouteLazyImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/forgot-password/route.lazy').then((d) => d.Route),
)

const RegisterRouteRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/register/route.lazy').then((d) => d.Route),
)

const MeRouteRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/me/route.lazy').then((d) => d.Route))

const LoginRouteRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/route.lazy').then((d) => d.Route))

const IndexRouteLazyRoute = IndexRouteLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index/route.lazy').then((d) => d.Route))

const ResetPasswordCodeRouteLazyRoute = ResetPasswordCodeRouteLazyImport.update(
  {
    id: '/reset-password/$code',
    path: '/reset-password/$code',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/reset-password/$code/route.lazy').then((d) => d.Route),
)

const VerifyEmailCodeRouteRoute = VerifyEmailCodeRouteImport.update({
  id: '/verify-email/$code',
  path: '/verify-email/$code',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/verify-email/$code/route.lazy').then((d) => d.Route),
)

const BuilderIdRouteRoute = BuilderIdRouteImport.update({
  id: '/builder/$id',
  path: '/builder/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/builder/$id/route.lazy').then((d) => d.Route),
)

const BuilderIndexRouteRoute = BuilderIndexRouteImport.update({
  id: '/builder/',
  path: '/builder/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/builder/index/route.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRoute
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRoute
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/builder/': {
      id: '/builder/'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderIndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/builder/$id': {
      id: '/builder/$id'
      path: '/builder/$id'
      fullPath: '/builder/$id'
      preLoaderRoute: typeof BuilderIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/verify-email/$code': {
      id: '/verify-email/$code'
      path: '/verify-email/$code'
      fullPath: '/verify-email/$code'
      preLoaderRoute: typeof VerifyEmailCodeRouteImport
      parentRoute: typeof rootRoute
    }
    '/reset-password/$code': {
      id: '/reset-password/$code'
      path: '/reset-password/$code'
      fullPath: '/reset-password/$code'
      preLoaderRoute: typeof ResetPasswordCodeRouteLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteLazyRoute
  '/login': typeof LoginRouteRoute
  '/me': typeof MeRouteRoute
  '/register': typeof RegisterRouteRoute
  '/forgot-password': typeof ForgotPasswordRouteLazyRoute
  '/builder': typeof BuilderIndexRouteRoute
  '/builder/$id': typeof BuilderIdRouteRoute
  '/verify-email/$code': typeof VerifyEmailCodeRouteRoute
  '/reset-password/$code': typeof ResetPasswordCodeRouteLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRouteLazyRoute
  '/login': typeof LoginRouteRoute
  '/me': typeof MeRouteRoute
  '/register': typeof RegisterRouteRoute
  '/forgot-password': typeof ForgotPasswordRouteLazyRoute
  '/builder': typeof BuilderIndexRouteRoute
  '/builder/$id': typeof BuilderIdRouteRoute
  '/verify-email/$code': typeof VerifyEmailCodeRouteRoute
  '/reset-password/$code': typeof ResetPasswordCodeRouteLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRouteLazyRoute
  '/login': typeof LoginRouteRoute
  '/me': typeof MeRouteRoute
  '/register': typeof RegisterRouteRoute
  '/forgot-password': typeof ForgotPasswordRouteLazyRoute
  '/builder/': typeof BuilderIndexRouteRoute
  '/builder/$id': typeof BuilderIdRouteRoute
  '/verify-email/$code': typeof VerifyEmailCodeRouteRoute
  '/reset-password/$code': typeof ResetPasswordCodeRouteLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/me'
    | '/register'
    | '/forgot-password'
    | '/builder'
    | '/builder/$id'
    | '/verify-email/$code'
    | '/reset-password/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/me'
    | '/register'
    | '/forgot-password'
    | '/builder'
    | '/builder/$id'
    | '/verify-email/$code'
    | '/reset-password/$code'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/me'
    | '/register'
    | '/forgot-password'
    | '/builder/'
    | '/builder/$id'
    | '/verify-email/$code'
    | '/reset-password/$code'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRouteLazyRoute: typeof IndexRouteLazyRoute
  LoginRouteRoute: typeof LoginRouteRoute
  MeRouteRoute: typeof MeRouteRoute
  RegisterRouteRoute: typeof RegisterRouteRoute
  ForgotPasswordRouteLazyRoute: typeof ForgotPasswordRouteLazyRoute
  BuilderIndexRouteRoute: typeof BuilderIndexRouteRoute
  BuilderIdRouteRoute: typeof BuilderIdRouteRoute
  VerifyEmailCodeRouteRoute: typeof VerifyEmailCodeRouteRoute
  ResetPasswordCodeRouteLazyRoute: typeof ResetPasswordCodeRouteLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteLazyRoute: IndexRouteLazyRoute,
  LoginRouteRoute: LoginRouteRoute,
  MeRouteRoute: MeRouteRoute,
  RegisterRouteRoute: RegisterRouteRoute,
  ForgotPasswordRouteLazyRoute: ForgotPasswordRouteLazyRoute,
  BuilderIndexRouteRoute: BuilderIndexRouteRoute,
  BuilderIdRouteRoute: BuilderIdRouteRoute,
  VerifyEmailCodeRouteRoute: VerifyEmailCodeRouteRoute,
  ResetPasswordCodeRouteLazyRoute: ResetPasswordCodeRouteLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/me",
        "/register",
        "/forgot-password",
        "/builder/",
        "/builder/$id",
        "/verify-email/$code",
        "/reset-password/$code"
      ]
    },
    "/": {
      "filePath": "index/route.lazy.tsx"
    },
    "/login": {
      "filePath": "login/route.tsx"
    },
    "/me": {
      "filePath": "me/route.tsx"
    },
    "/register": {
      "filePath": "register/route.tsx"
    },
    "/forgot-password": {
      "filePath": "forgot-password/route.lazy.tsx"
    },
    "/builder/": {
      "filePath": "builder/index/route.tsx"
    },
    "/builder/$id": {
      "filePath": "builder/$id/route.tsx"
    },
    "/verify-email/$code": {
      "filePath": "verify-email/$code/route.tsx"
    },
    "/reset-password/$code": {
      "filePath": "reset-password/$code/route.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
